### ISSUE TITLE
Video

### ISSUE THREAD

**Issue by smeyer98** [haakon023/VikingGame#124]
until Sunday: Idea
on Sunday: Filming, Cut

**Comment by the-nilosch** [comment]
Take some Ideas from this not-Software-Architecture-Example:

https://www.youtube.com/watch?v=tF6ow5rQnio&ab_channel=Aimchess.com

* Mention VIKING STOP a lot, and also always use the same sound and animation
* have a natural voice
* jokes
* support spoken text with random pictures, no matter if they have copyright blur etc
